#!/bin/fish

# Script simples em fishscript, para alterar o gtk 

function Xreset
    echo "Resetando o xsettings "
    killall xsettingsd
    xsettingsd --config ~/.config/bspwm/xsettingsd &
    dunstify "xsettings resetado"
end


Xreset



